package org.omg.IOP;


/**
* org/omg/IOP/ENCODING_CDR_ENCAPS.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/jenkins/workspace/8-2-build-windows-x64-cygwin/jdk8u341/2692/corba/src/share/classes/org/omg/PortableInterceptor/IOP.idl
* Thursday, June 16, 2022 3:52:35 PM UTC
*/

public interface ENCODING_CDR_ENCAPS
{

  /**
   * The CDR Encapsulation encoding.
   * @see CodecFactory
   */
  public static final short value = (short)(0);
}
